### ISSUE TITLE
console I/O errors

### ISSUE THREAD

**Issue by Cruwzky** [jpenilla/squaremap#66]
My console is spammed with the error in the pastebin.

How do I fix this? There is enough space and the disk is performing fine.

https://bin.bloom.host/xutigiwugi

**Comment by mirivlad** [comment]
Check file and directory permissions, if you sure have enough space on disk.
Also - directory for PNG images may be placed on other disk.

**Comment by jaknz** [comment]
I have the same thing since upgrading to 1.19.1 (on Purpur). It's definitely not a file permissions issue in my case. This just repeats non-stop.
`[20:11:55] [Server thread/WARN]: [squaremap] Task #9 for squaremap v1.1.6 generated an exception
java.lang.NoSuchMethodError: 'boolean net.minecraft.server.level.EntityPlayer.bY()'
	at xyz.jpenilla.squaremap.common.task.UpdatePlayers.lambda$run$0(UpdatePlayers.java:67) ~[squaremap-paper-mc1.19-1.1.6.jar:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at xyz.jpenilla.squaremap.common.task.UpdatePlayers.lambda$run$1(UpdatePlayers.java:63) ~[squaremap-paper-mc1.19-1.1.6.jar:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at xyz.jpenilla.squaremap.common.task.UpdatePlayers.run(UpdatePlayers.java:60) ~[squaremap-paper-mc1.19-1.1.6.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.1.jar:git-Purpur-1743]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.1.jar:git-Purpur-1743]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1518) ~[purpur-1.19.1.jar:git-Purpur-1743]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:485) ~[purpur-1.19.1.jar:git-Purpur-1743]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1442) ~[purpur-1.19.1.jar:git-Purpur-1743]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[purpur-1.19.1.jar:git-Purpur-1743]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310) ~[purpur-1.19.1.jar:git-Purpur-1743]
	at java.lang.Thread.run(Unknown Source) ~[?:?]`

**Comment by jpenilla** [comment]
@jaknz that is not the same issue. your issue is a duplicate of #67
